/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TokenVestingContractJson } from "../TokenVesting.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace TokenVestingTypes {
  export type Fields = {
    beneficiary: Address;
    durationMs: bigint;
    startMs: bigint;
    token: HexString;
    tokenReleased: bigint;
  };

  export type State = ContractState<Fields>;

  export type TokenReleasedEvent = ContractEvent<{ amount: bigint }>;

  export interface CallMethodTable {
    release: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    vestedAmount: {
      params: CallContractParams<{ timestamp: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    release: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    vestedAmount: {
      params: SignExecuteContractMethodParams<{ timestamp: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  TokenVestingInstance,
  TokenVestingTypes.Fields
> {
  encodeFields(fields: TokenVestingTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { TokenReleased: 0 };
  consts = { ErrorCodes: { InvalidWithdrawAmount: BigInt("0") } };

  at(address: string): TokenVestingInstance {
    return new TokenVestingInstance(address);
  }

  tests = {
    release: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenVestingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "release", params, getContractByCodeHash);
    },
    vestedAmount: async (
      params: TestContractParamsWithoutMaps<
        TokenVestingTypes.Fields,
        { timestamp: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "vestedAmount", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: TokenVestingTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TokenVesting = new Factory(
  Contract.fromJson(
    TokenVestingContractJson,
    "=6-2+39=2-2+91=11-1+8=24+0016007e0208616d6f756e743a20=226",
    "3268309939c47148debad7ad4d138b32a718695e4e030a000e5dd15860c61f87",
    []
  )
);
registerContract(TokenVesting);

// Use this class to interact with the blockchain
export class TokenVestingInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenVestingTypes.State> {
    return fetchContractState(TokenVesting, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeTokenReleasedEvent(
    options: EventSubscribeOptions<TokenVestingTypes.TokenReleasedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenVesting.contract,
      this,
      options,
      "TokenReleased",
      fromCount
    );
  }

  view = {
    release: async (
      params?: TokenVestingTypes.CallMethodParams<"release">
    ): Promise<TokenVestingTypes.CallMethodResult<"release">> => {
      return callMethod(
        TokenVesting,
        this,
        "release",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    vestedAmount: async (
      params: TokenVestingTypes.CallMethodParams<"vestedAmount">
    ): Promise<TokenVestingTypes.CallMethodResult<"vestedAmount">> => {
      return callMethod(
        TokenVesting,
        this,
        "vestedAmount",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    release: async (
      params: TokenVestingTypes.SignExecuteMethodParams<"release">
    ): Promise<TokenVestingTypes.SignExecuteMethodResult<"release">> => {
      return signExecuteMethod(TokenVesting, this, "release", params);
    },
    vestedAmount: async (
      params: TokenVestingTypes.SignExecuteMethodParams<"vestedAmount">
    ): Promise<TokenVestingTypes.SignExecuteMethodResult<"vestedAmount">> => {
      return signExecuteMethod(TokenVesting, this, "vestedAmount", params);
    },
  };

  async multicall<Calls extends TokenVestingTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TokenVestingTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends TokenVestingTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<TokenVestingTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | TokenVestingTypes.MultiCallParams
      | TokenVestingTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      TokenVesting,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
